algoritmo "semnome"
var
   N1, N2, N3, M: Real
inicio
      EscrevaL("-------------------------------")
      EscrevaL(" Média De Um Aluno ")
      EscrevaL("-------------------------------")
      Escreva("Digite a Primeira Nota: ")
      Leia(N1)
      Escreva("Digite a Segunda Nota: ")
      Leia(N2)
      Escreva("Digite a Terceira Nota: ")
      Leia(N3)
      M <- (N1 + N2 + N3) / 2
      Escreva("A Média do ALuno é ", M)
fimalgoritmo