algoritmo "SuperContador"
var
   C: Inteiro
inicio
      EscrevaL(" ==================== ")
      EscrevaL(" |       MENU       | ")
      EscrevaL(" ==================== ")
      EscrevaL(" | [1] De 1 até 10  | ")
      EscrevaL(" | [2] De 10 até 1  | ")
      EscrevaL(" | [3] Sair         | ")
      EscrevaL(" ==================== ")
      Leia(C)
      Escolha C
              Caso 1
                   C <- 1
      FimEscolha
fimalgoritmo