algoritmo "Ex0006"
var
   N1: Real
inicio
      Escreva("Digite um Numero: ")
      Leia(N1)
      Se (N1 > 80) entao
         Escreva("O Numero Digitado é Maior que 80")
      Senao
           Se (N1 < 25) entao
              Escreva("O Numero Digitado é Menor que 25")
           Senao
                Se (N1 = 40) entao
                   Escreva(" O Numero Digitado é igual a 40 ")
                FimSe
           FimSe
      FimSe
fimalgoritmo