algoritmo "Ex0001"
//Joaquim Fernandes
//Exercicios de Aplicação
var
   N1, N2, S: Real
inicio
      EscrevaL(" ------------------------- ")
      EscrevaL(" - Soma de Dois Numeros  - ")
      EscrevaL(" ------------------------- ")
      Escreva(" Digite Um Número: ")
      Leia(N1)
      Escreva(" Digite Outro Número: ")
      Leia(N2)
      S <- N1 + N2
      Escreva(" A Soma entre os Dois Numeros Digitados é:", S)
      EscrevaL(" ------------------------- ")
fimalgoritmo